# Site settings
title: CHEZ Joo
email: yyjess@gmail.com
description: "Joo is a handsome teenager cat starting to know about life and love. "
baseurl: ""
url: "http://www.yyjess.org"
#twitter_username: 
#github_username:  

# Build settings
markdown: redcarpet

permalink: pretty
